name: Build and Deploy

on:
  push:
    tags: ["test_v*"]


jobs:
  tests:
    runs-on: ubuntu-latest

    


    steps:
      - uses: actions/checkout@v3

      - name: Print github.ref_name
        run: echo ${{ github.ref_name }}
