name: Build and Deploy

on:
  push:
    branches: ["master"]


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: ${{ github.ref }}  # Inherits tag name from push event

    steps:
      - uses: actions/checkout@v3

      - name: Print github.ref
        run: echo ${{ matrix.tag }}
