name: Build and Deploy

on: push # Triggers the workflow on push events
#   push:
#     tags:
#       - 'test_v[0-9]+.[0-9]+.[0-9]+'  # Matches tags like test_v1.2.3
#       - 'prod_v[0-9]+.[0-9]+.[0-9]+'  # Matches tags like prod_v1.2.3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: ${{ github.ref }}  # Inherits tag name from push event
        base_image:
          - test:python:3.9  # Base image for test tags
          - prod:python:3.8  # Base image for prod tags

    steps:
      - uses: actions/checkout@v3

      - name: Check tag type
        run: |
          if [[ ${{ matrix.tag }} =~ ^test_v ]]; then
            echo "Building test image"
          else
            echo "Building production image"
          fi

